### ISSUE TITLE
Numbers.roundTo(190.005, 2) not rounding correctly

### ISSUE THREAD

**Issue by mamarcus17** [TeamworkGuy2/ts-mortar#1]
We noticed a rounding bug in our code when we attempted to do the following: `Numbers.roundTo(190.005, 2)`. The result is `190.000`, when I am expecting `190.01`.

I noticed that Numbers.roundTo() uses "Number.toFixed(decimalPlaces)" to do the rounding, but apparently there is an error with toFixed() as explained here: https://www.sitepoint.com/number-tofixed-rounding-errors-broken-but-fixable/

**Comment by TeamworkGuy2** [comment]
Thanks for bug report, I'll try and take a look at it this weekend.

**Comment by TeamworkGuy2** [comment]
Should be fixed now with version `0.18.1` (see commit https://github.com/TeamworkGuy2/ts-mortar/commit/55218d9aa824f5e94cd24a9041c78794bc86dd58 for implementation and test cases).
